---
- name: Make sure bareos-client is installed
  ansible.builtin.apt:
    name: bareos-client

- name: Upload client backup scripts
  ansible.builtin.copy:
    src: client/opt/backup-scripts/
    dest: /opt/backup-scripts/
    mode: "0700"
    directory_mode: "0700"
    owner: root
    group: root

- name: Create config dir on client
  ansible.builtin.file:
    path: /etc/bareos/bareos-fd.d/director
    state: directory
    owner: root
    group: bareos
    mode: "0750"

- name: Make sure director's IP is defined on host
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ bareos_director.ip }}"
    line: "{{ bareos_director.ip }} {{ bareos_director.name }}"
  when:
    - bareos_director.ip is defined
    - bareos_director.name is defined

# This block is not idempotent and should be used only as one-time update
- name: Upgrade BareOS
  when: bareos_version is defined
  block:
    - name: Stop before upgrade
      ansible.builtin.service:
        name: bareos-fd
        state: stopped

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      failed_when: true

    - name: Upgrade to specific version
      ansible.builtin.apt:
        name:
          - "bareos-bconsole={{ bareos_version }}"
          - "bareos-client={{ bareos_version }}"
          - "bareos-common={{ bareos_version }}"
          - "bareos-filedaemon={{ bareos_version }}"
        allow_unauthenticated: true

    - name: Start after upgrade
      ansible.builtin.service:
        name: bareos-fd
        state: started
